### PR TITLE
Added support for NET Standard 1.3

### PR DESCRIPTION
**Pull request by eallegretta**

### CODE REVIEW

**Comment by grubman** [comment]
I'm not sure what is the added value by this PR.

**Comment by eallegretta** [comment]
Well, since net standard 2 is on its way it probably does not make any sense now, but before it allowed you to use this library on net standard projects

**Comment by rwkarg** [comment]
For comment on the value, we have .NET Core projects that are using a NetStandard library to allow Syslog writing.

We aren't using the @eallegretta fork since there are some bug fixes in this project but not in the fork. We've taken this repo and locally created NetStandard 1.3 packages similar to the fork and are currently maintaining both (so we get NetStandard + bug fixes not in the fork). This is obviously not an ideal state.

The ideal state would be a NetStandard package in one repository (so bug fixes have one repository to go in to) and a second non-NetStandard (full framework) package with the encrypted TCP serializer since that's not supported in NetStandard 1.X.

**Comment by grubman** [comment]
@rwkarg, I do prefer not to manage two packages.

**Pull request closed without merging**
