### PR TITLE
Fix TCP OctetCounting Send to write to the stream at once.

### PR DESCRIPTION
**Pull request by thesourcerer**
Following our chat, this pull request fixes OctetCounting/TCP send so Kiwi server won't split the message to 2 messages after the count section.

### CODE REVIEW

**Comment by nE0sIghT** [comment]
Why that was hacked in SyslogNet client?
Why that was not **just fixes** in broken server, btw @thesourcerer did you filled issue for them?

Which RFC part **oblige** client to send data in one TCP packet (I think you try to resolve that issue)?
Do you sure that *writing* data in one bulk (in C#) is equal to *send* data in one packet?

**Comment by thesourcerer** [comment]
@nE0sIghT , you are correct that there is nothing (that I could find) in the RFC that oblige sending all the data at once.
I did not find anything in Kiwi's documentation to explain their behavior.
I did not make a special effort to report a bug to them for 2 reasons:
1. Could not find a "report a bug" option in their website, if you do, I will be happy to report it.
2. Even if this is indeed a bug in Kiwi, and they fix it for future versions, we still want to support the large install base of existing Kiwi Servers that might not be running the latest potentially fixed version, and this change solves the problem without harming this library in any way logically, that is, if the code would have been written initially by another developer,  it's not unlikely that this "one send" implementation detail will be used even if the Kiwi problem was not known.

As to C# implementation, checking [referencesource.microsoft.com](https://referencesource.microsoft.com/#System/net/System/Net/Sockets/Socket.cs,ab342a540359909f), shows that it simply uses [winsock send method](https://msdn.microsoft.com/en-us/library/windows/desktop/ms740149(v=vs.85).aspx), which to my best understanding from this page, uses a single packet (also, in effect, this has solved the problem in Kiwi)

**Comment by nE0sIghT** [comment]
> Could not find a "report a bug"

I [Googled this for you](https://customerportal.solarwinds.com/support/submit-a-ticket/). Don't say thanks to me.

> we still want to support the large install base of existing Kiwi Servers

**You** (I hope that @grubman merged this by mistake) want this.
**I want** that SyslogNet will not became bunch of shitty hacks

> it simply uses winsock send method

Indeed!

> which to my best understanding from this page, uses a single packet

**Why** did you make such weird conclusion?
Did you read this? 
```If no error occurs, send returns the total number of bytes sent, which can be less than the number requested to be sent in the len parameter.```
OS can pack your buffer in as much TCP segments as it wants. It may even did not sent all your data if socket buffer is full.

This should (or should not - I don't care really) be fixed in broken server, not in SyslogNet.
This PR should be reverted.

**Comment by grubman** [comment]
In my opinion the reasons for this PR are less important.
You should judge the result.

The result is a clean code which could have been written from the beginning. There is no obvious patching or addressing a special server implementation. While the original functionality is kept the same and there was no regression, the new version allows more users to use this library.

That is why I think that unless there is some kind of regression bug, the PR should not be reverted.

**Comment by nE0sIghT** [comment]
> The result is a clean code

Introducing useless memory buffer which will be GCed is a "clean code" and "same"?
What in the hell are you talking about? This **is** monkey patching for **broken** server implementation.

Accepting such weird changes is worse than just do nothing.

Forking and unsubscribing, regards.

**Comment by thesourcerer** [comment]
@nE0sIghT , I am familiar with the link you googled and it is not a page for opening bugs.
it's a page for opening a support ticket and I quote: "to the products that you own".
I don't own Kiwi. The product I am working on is simply implementing integration with several syslog servers, Kiwi is one of them.
And for the send method, please note from the help page and I quote: 
"care must be taken not to exceed the maximum packet size of the underlying provider"
It is possible I am misinterpreting this, but it sounds right to me.

As to the complaint about the added allocation of MemoryStream:
I have tested the code in a stress environment and saw no negative impact on performance.
Please keep in mind that I might have allocated another object, but the original code calling Write several times, caused **several**  additional allocation inside the NetworkStream.Write method that were saved.

If this change was actually making a significant change that without the kiwi problem no one would write it, I might have agreed that we are on a "gray" area, but I don't believe this change was such.
Also, a nicely written library that might have a "very clean" code in ones aspect but fails proper integration with substantial install base of syslog servers, might look nice engineering wise, but will not be as useful as it could be.

**Comment by nE0sIghT** [comment]
@thesourcerer 
No reason to ping me since only project "collaborator" (with **one usefull** project commit ever) said that this PR is acceptable for this project.

I'm not interested in further discussion, but since I was pinged:

> it is not a page for opening bugs

It's not a reason to commit hacks to valid clients following RFC.

> original code calling Write several times, caused several additional allocation inside the NetworkStream

This is only reasonable argument for now which **may** be reviewed, however as you said "I have tested the code in a stress environment and so no negative impact on performance" - I believe that there is no "positive" impact at all.
So as I said before - this PR is useless.

> but I don't believe this change was such

You don't need to believe. Look to the sources of **valid** syslog server, eg rsyslog.
You hacked **valid** client, but should fix **broken** server.
Do right things, don't do wrong things.

> fails proper integration with substantial install base of syslog servers

One **broken** server is not "syslog servers".

**Comment by thesourcerer** [comment]
Got curious when you mentioned rsyslog. 
So I went ahead and peaked at the corresponding code for sending via TCP in their syslog client implementation as I figured that if they are considered a  "valid" product, they wouldn't allow themselves to fail proper integration with Kiwi. Thought I might find a nicer solution there, but surprise, they used a similar method as I did - First pre building the message in a memory buffer, then sending it **once**.
[Relevant code here](https://github.com/rsyslog/rsyslog/blob/master/runtime/tcpclt.c)
(Don't get distracted by the loop, it's for resends in case of network failures.)

**Pull request merged**
